# Generated by Django 5.1.7 on 2025-03-14 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('departamento', models.CharField(choices=[('Administracion_y_Finanzas', 'Departamento de Administración y Finanzas'), ('Accion_Sanitaria', 'Departamento de Acción Sanitaria'), ('Juridico', 'Departamento Jurídico'), ('Salud_Publica', 'Departamento de Salud Pública'), ('Compin_Cautin', 'Compin Cautín'), ('Compin_Malleco', 'Compin Malleco'), ('Seremi_de_Salud', 'Seremi de Salud'), ('Gestion_y_Desarrollo_Personas', 'Departamento de Gestión y Desarrollo de Personas'), ('Bodega', 'Departamento de Bodega')], max_length=50, verbose_name='Departamento')),
                ('es_jefe', models.BooleanField(default=False, verbose_name='Es Jefe')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=50, unique=True, verbose_name='Código de Barra')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('categoria', models.CharField(choices=[('Insumos_Aseo', 'Insumos Aseo'), ('Insumos_Escritorio', 'Insumos Escritorio'), ('EPP', 'EPP'), ('Emergencias_y_Desastres', 'Emergencias y Desastres'), ('Folletoria', 'Folletoría'), ('Otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('rut_proveedor', models.CharField(max_length=12, verbose_name='Rut del Proveedor')),
                ('guia_despacho', models.CharField(max_length=50, verbose_name='Guía de Despacho')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('orden_compra', models.CharField(max_length=50, verbose_name='Orden de Compra')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.IntegerField(verbose_name='Número de Acta')),
                ('fecha_entrega', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('funcionario', models.CharField(max_length=100, verbose_name='Funcionario')),
                ('jefe_subdepartamento', models.CharField(max_length=100, verbose_name='Jefe del Subdepartamento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Entregada')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable del Acta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de Transacción')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('rut_proveedor', models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut del Proveedor')),
                ('guia_despacho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guía de Despacho')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('orden_compra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Compra')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto', verbose_name='Producto')),
            ],
        ),
    ]
