# Generated by Django 5.1.7 on 2025-03-21 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(choices=[('Seremi de Salud', 'Seremi de Salud'), ('Gabinete', 'Gabinete'), ('Departamento Jurídico', 'Departamento Jurídico'), ('Compin Cautín', 'Compin Cautín'), ('Departamento de Acción Sanitaria (DAS)', 'Departamento de Acción Sanitaria (DAS)'), ('Departamento de Administración y Finanzas (DAF)', 'Departamento de Administración y Finanzas (DAF)'), ('Departamento de Gestión y Desarrollo de Personas', 'Departamento de Gestión y Desarrollo de Personas'), ('Departamento de Salud Pública', 'Departamento de Salud Pública'), ('Oficina Provincial Malleco (OPM)', 'Oficina Provincial Malleco (OPM)')], max_length=100)),
                ('es_jefe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12)),
                ('guia_despacho', models.CharField(blank=True, max_length=50)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.IntegerField(unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('generador', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12)),
                ('guia_despacho', models.CharField(blank=True, max_length=50)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto')),
            ],
        ),
    ]
