# Generated by Django 5.0.3 on 2025-04-14 14:10

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(choices=[('Seremi de Salud', 'Seremi de Salud'), ('Gabinete', 'Gabinete'), ('Departamento Jurídico', 'Departamento Jurídico'), ('Compin Cautín', 'Compin Cautín'), ('Departamento de Acción Sanitaria (DAS)', 'Departamento de Acción Sanitaria (DAS)'), ('Departamento de Administración y Finanzas (DAF)', 'Departamento de Administración y Finanzas (DAF)'), ('Departamento de Gestión y Desarrollo de Personas', 'Departamento de Gestión y Desarrollo de Personas'), ('Departamento de Salud Pública', 'Departamento de Salud Pública'), ('Oficina Provincial Malleco (OPM)', 'Oficina Provincial Malleco (OPM)')], max_length=100)),
                ('es_jefe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('categoria', models.CharField(blank=True, choices=[('Insumos de Aseo', 'Insumos de Aseo'), ('Insumos de Escritorio', 'Insumos de Escritorio'), ('EPP', 'EPP'), ('Emergencias y Desastres', 'Emergencias y Desastres'), ('Folletería', 'Folletería'), ('Otros', 'Otros')], max_length=100)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12)),
                ('guia_despacho', models.CharField(blank=True, max_length=50)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(help_text='Ingrese el RUT sin puntos ni guiones (ejemplo: 12345678K)', max_length=12, unique=True, validators=[accounts.models.validate_rut])),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'permissions': [('can_access_admin', 'Puede acceder al panel de administración'), ('can_manage_users', 'Puede gestionar usuarios'), ('can_manage_departments', 'Puede gestionar departamentos'), ('can_edit', 'Puede editar registros')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.IntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('numero_siscom', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generador')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto')),
            ],
            options={
                'unique_together': {('numero_acta', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12)),
                ('guia_despacho', models.CharField(blank=True, max_length=50)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('acta_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.actaentrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Jefatura', 'Jefatura'), ('Jefatura Subrogante', 'Jefatura Subrogante'), ('Secretaria', 'Secretaria'), ('Secretaria Subrogante', 'Secretaria Subrogante')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='accounts.departamento')),
            ],
            options={
                'unique_together': {('departamento', 'tipo')},
            },
        ),
    ]
