# Generated by Django 5.1.7 on 2025-03-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Insumos de Aseo', 'Insumos de Aseo'), ('Insumos de Escritorio', 'Insumos de Escritorio'), ('EPP', 'EPP'), ('Emergencias y Desastres', 'Emergencias y Desastres'), ('Folletería', 'Folletería'), ('Otros', 'Otros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
