# Generated by Django 5.0.3 on 2025-04-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_responsable', to='accounts.responsable', verbose_name='Responsable'),
        ),
    ]
