# Generated by Django 5.1.7 on 2025-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='numero_siscom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
