# Generated by Django 5.1.7 on 2025-03-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_actaentrega_numero_acta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
            ],
        ),
    ]
