# Generated by Django 5.1 on 2025-06-26 18:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_categoria_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_admin', 'Acceso al panel de administración'), ('can_manage_users', 'Gestión de usuarios'), ('can_manage_departments', 'Gestión de departamentos'), ('can_edit', 'Edición de registros')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(help_text='RUT sin puntos ni guiones (ej. 12345678K)', max_length=12, unique=True, validators=[accounts.models.validate_rut]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
