# Generated by Django 5.1.7 on 2025-03-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_numeroacta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumeroActa',
        ),
    ]
