# Generated by Django 5.1 on 2025-06-27 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_alter_customuser_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_vencimiento',
            field=models.BooleanField(default=False, verbose_name='¿Tiene fecha de vencimiento?'),
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock del lote')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('numero_lote', models.CharField(blank=True, max_length=50, verbose_name='Número de lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='accounts.producto')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
