# Generated by Django 5.1 on 2025-06-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_producto_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproducto',
            name='numero_lote',
            field=models.IntegerField(verbose_name='Número de lote'),
        ),
        migrations.AlterUniqueTogether(
            name='loteproducto',
            unique_together={('producto', 'numero_lote')},
        ),
    ]
