# Generated by Django 5.1.7 on 2025-03-31 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_numeroacta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Jefatura', 'Jefatura'), ('Jefatura Subrogante', 'Jefatura Subrogante'), ('Secretaria', 'Secretaria'), ('Secretaria Subrogante', 'Secretaria Subrogante')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='accounts.departamento')),
            ],
            options={
                'unique_together': {('departamento', 'tipo')},
            },
        ),
    ]
