# Generated by Django 5.1.7 on 2025-04-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_departamento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='acta_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.actaentrega'),
        ),
    ]
