# Generated by Django 5.1.7 on 2025-04-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transaccion_acta_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
